[tool.poetry]
name = "nikoli-puzzle-solver"
version = "0.1.0"
description = ""
authors = ["Kevin Chen"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
